java:
  awt:
    headless: true

server:
  servlet:
    register-default-servlet: true
    encoding:
      enabled: true
      charset: UTF-8
      force: true
      force-response: true
      force-request: true
    session:
      cookie:
        max-age: 0
      tracking-modes: COOKIE
  error:
    whitelabel:
      enabled: true
  tomcat:
    uri-encoding: UTF-8
    max-swallow-size: 800MB

spring:
  profiles:
    active: local # 기본 프로파일 설정
    
  servlet:
    multipart: # 최대 파일 크기 설정
      maxFileSize: 10MB
      maxRequestSize: 10MB
  session:
    store-type: none # jsession 해제
  jpa:
    open-in-view: false # OIV 설정 해제
    properties:
      hibernate:
        auto_quote_keyword: true
        # globally_quoted_identifiers: true
  
  # 핸들러가 없을 시 404를 띄우기 위한 형태
  # https://velog.io/@gillog/Spring-404-Error-Custom%ED%95%98%EA%B8%B0-ExceptionHandler%EC%82%AC%EC%9A%A9-NoHandlerFoundException-Throw-%EC%95%88%EB%90%A0%EB%95%8C
  web:
    resources:
      add-mappings: false  
  mvc:
    throw-exception-if-no-handler-found: true

#springdoc:
#  api-docs:
#    path: /api-docs